{% set name = "careamics-napari" %}
{% set version = "0.0.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/careamics_napari-{{ version }}.tar.gz
  sha256: 1c38ae81e831176929c10bc3b4d6df6975ce6fa252cfcfaf7a0a701d864d0905

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42.0.0
    - wheel
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - qtpy
    - psygnal
    - pyqtgraph
    - napari
    - careamics >=0.0.4
    - careamics-portfolio

test:
  imports:
    - careamics_napari
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://careamics.github.io
  summary: napari plugin providing an interface to CAREamics.
  description: |
    CAREamics is a PyTorch library aimed at simplifying the use of Noise2Void and its many
    variants and cousins (CARE, Noise2Noise, N2V2, P(P)N2V, HDN, MicroSplit etc.).

    This package provides an interface via the napari image viewer.
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/CAREamics/careamics-napari
  doc_url: https://careamics.github.io
  doc_source_url: https://github.com/CAREamics/careamics.github.io

extra:
  recipe-maintainers:
    - jdeschamps
